### ISSUE TITLE
Faulty JavaScript generated from AutocompleteConfiguration

### ISSUE THREAD

**Issue by juselius** [intellifactory/websharper.jqueryui#7]
I'm trying to use JQueryUI autocomplete using a (async) callback. However, the following WebSharper snippet generates faulty JavaScript (see below). 

```fsharp
open WebSharper
open WebSharper.Html.Client
[<JavaScript>]
let Duh () =
    let completer (req : JQueryUI.AutocompleteRequest, respf : array<JQueryUI.AutocompleteItem> -> unit) =
        respf [| {Label = "foo"; Value = "bar" } |]
   let input = Input []
   let conf = JQueryUI.AutocompleteConfiguration()
   conf.SourceCallback <- completer
   JQueryUI.Autocomplete.New(input, conf) |> ignore
    input 
```
In the generated code below, the autocomplete 'source' property is left unset, and a property  called 'source3' is set instead. This give a runtime error when trying to call the callback (which is null). Changing the JavaScript from source3 to source fixes the problem, but then it crashes with "Uncaught TypeError: Cannot read property 'call' of undefined" in line 6 below.  

```javascript
Duh:function()
    {
     var completer,arg10,input,conf;
     completer=function(tupledArg)
     {
      return tupledArg[1].call(null,[{
       label:"foo",
       value:"bar"
      }]);
     };
     arg10=Runtime.New(T,{
      $:0
     });
     input=Tags.Tags().NewTag("input",arg10);
     conf=AutocompleteConfiguration.New();
     conf.source3=completer;
     Autocomplete.New1(input,conf);
     return input;
    }
   }
  }
 });
```

Am I doing something wrong?

I'm using F# in VS 2015 and  F# 3.1 in mono under Linux. I have tested with:

WebSharper.3.6.2.220
WebSharper.Formlets.3.6.2.68
WebSharper.Html.3.6.2.12
WebSharper.JQueryUI.3.6.1.285

**Comment by juselius** [comment]
Ok, I figured it out. The implementation was all wrong, and only worked for simple array sources. Incidentally this was also the only case which was tested for in the test suite. I will file a pull request shortly, if anyone cares.

**Comment by Tarmil** [comment]
Thanks for the PR! Tested and merged.
